#!/bin/bash
#
# Usage:
#    ./run YEAR DAY
#
set -eu

filename="$1"
output="${filename%.cpp}"

shift

"${CXX-g++}" -Wall -Wextra -pedantic -std=c++17 -O2 -Wshadow -Wformat=2 -Wfloat-equal -Wconversion -Wlogical-op -Wshift-overflow=2 -Wduplicated-cond -Wcast-qual -Wcast-align -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -D_FORTIFY_SOURCE=2 "${filename}" -o "${output}"

time "${output}" "$@"
