#!/bin/bash
#
# Usage:
#    ./run YEAR DAY
#
CPP_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
cd "${CPP_DIR}"

if [[ $# -ne 2 ]]; then
    echo "Missing arguments:"
    echo "./run YEAR DAY"
    exit 1
fi

year=$1
day=$(echo $2 | awk '{printf "%02d\n", $0;}')

echo "${CPP_DIR}/${year}/${day}"
"${CPP_DIR}/${year}/${day}"
