#!/bin/bash
#
# Usage:
#     ../get-input 4
#
# Should download the appropriate year/day input as #_input (01_input or 10_input)

PROJ_DIR=$(dirname "$(greadlink -f "$0")")
SESSION=$(cat "${PROJ_DIR}/.session")

year=$(basename "${PWD}")
day="$1"

if [[ $# -eq 0 ]]; then
   echo "ERROR: No day passed"
   exit 1
fi

if [[ ${day} -lt 10 ]]; then
    full_day="0${day}"
else
    full_day="${day}"
fi

url="https://adventofcode.com/${year}/day/${day}/input"
input="${full_day}_input"

curl "${url}" \
  -H 'X-MAS: hi-eric-thank-you-for-making-aoc' \
  -H "cookie: session=${SESSION}" \
  --compressed > "${input}"

cat "${input}"
echo '^ '"${input}"